version: "3.4"

services:
  webhookio:
    image: webhookio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      URL_DATABASE: mongodb://mongo/example
    ports:
      - 8000:8000
    networks:
      - common
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - common
networks:
  common:
